import { StyleSheet } from "react-native";
import {
  COLORS,
  TYPOGRAPHY,
  SPACING,
  BORDER_RADIUS,
  SHADOWS,
} from "../../../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    ...TYPOGRAPHY.h2,
    color: COLORS.text,
    marginLeft: SPACING.sm,
  },
  headerRight: {
    flexDirection: "row",
    marginLeft: "auto",
  },
  editButton: {
    position: 'absolute',
    top: SPACING.lg,
    right: SPACING.lg,
    zIndex: 10,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    ...SHADOWS.md,
  },
  editButtonNew: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: COLORS.neutral[100],
    width: '47%',
    height: 45,
    borderWidth: 1,
    borderColor: COLORS.primary.main,
  },
  editButtonText: {
    ...TYPOGRAPHY.button,
    color: COLORS.primary.main,
    marginLeft: SPACING.xs,
    fontSize: 16,
  },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(244, 67, 54, 0.1)',
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: BORDER_RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.danger[500],
    width: '47%',
    height: 45,
  },
  deleteButtonText: {
    ...TYPOGRAPHY.button,
    color: COLORS.danger[500],
    marginLeft: SPACING.xs,
    fontSize: 16,
  },
  content: {
    flex: 1,
  },
  infoSection: {
    backgroundColor: COLORS.surface,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
  },
  goalName: {
    ...TYPOGRAPHY.h3,
    color: COLORS.text,
    marginBottom: SPACING.sm,
  },
  goalStatus: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: SPACING.md,
  },
  statusBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.primary.main,
  },
  statusText: {
    ...TYPOGRAPHY.caption,
    color: COLORS.white,
  },
  progressSection: {
    backgroundColor: COLORS.surface,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
  },
  progressTitle: {
    ...TYPOGRAPHY.subtitle1,
    color: COLORS.text,
    marginBottom: SPACING.md,
  },
  progressBar: {
    height: 20,
    backgroundColor: COLORS.neutral[200],
    borderRadius: 10,
    marginBottom: SPACING.md,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 10,
  },
  progressInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressText: {
    ...TYPOGRAPHY.body2,
    color: COLORS.text,
  },
  progressPercentage: {
    ...TYPOGRAPHY.subtitle2,
    color: COLORS.primary.main,
  },
  timeSection: {
    backgroundColor: COLORS.surface,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
  },
  timeTitle: {
    ...TYPOGRAPHY.subtitle1,
    color: COLORS.text,
    marginBottom: SPACING.md,
  },
  timeInfo: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  timeItem: {
    flex: 1,
    alignItems: "center",
  },
  timeLabel: {
    ...TYPOGRAPHY.caption,
    color: COLORS.textSecondary,
    marginBottom: SPACING.xs,
  },
  timeValue: {
    ...TYPOGRAPHY.body2,
    color: COLORS.text,
    textAlign: "center",
  },
  actionsSection: {
    padding: SPACING.lg,
  },
  addFundsForm: {
    marginBottom: SPACING.lg,
  },
  formButtons: {
    flexDirection: "row",
    marginTop: SPACING.sm,
  },
  statusButtons: {
    flexDirection: "row",
    marginTop: SPACING.lg,
  },
  offlineContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.warning[100],
    padding: SPACING.md,
    marginHorizontal: SPACING.lg,
    marginTop: SPACING.md,
    borderRadius: BORDER_RADIUS.md,
  },
  offlineText: {
    ...TYPOGRAPHY.body2,
    color: COLORS.warning[600],
    marginLeft: SPACING.sm,
    flex: 1,
  },
  notFoundContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: SPACING.xl,
  },
  notFoundText: {
    ...TYPOGRAPHY.h3,
    color: COLORS.text,
    marginTop: SPACING.md,
  },
  goalHeader: {
    backgroundColor: COLORS.surface,
    padding: SPACING.lg,
    alignItems: "center",
    marginBottom: SPACING.md,
  },
  iconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: SPACING.md,
  },
  goalDescription: {
    ...TYPOGRAPHY.body1,
    color: COLORS.textSecondary,
    textAlign: "center",
    marginBottom: SPACING.md,
  },
  amountContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: SPACING.lg,
  },
  amountColumn: {
    flex: 1,
    alignItems: "center",
  },
  amountLabel: {
    ...TYPOGRAPHY.caption,
    color: COLORS.textSecondary,
    marginBottom: SPACING.xs,
  },
  amountValue: {
    ...TYPOGRAPHY.subtitle1,
    color: COLORS.text,
  },
  formSection: {
    backgroundColor: COLORS.surface,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
  },
  actionSection: {
    backgroundColor: COLORS.surface,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
  },
  addFundsButton: {
    flexDirection: "row",
    backgroundColor: COLORS.primary.main,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderRadius: BORDER_RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
  },
  addFundsButtonText: {
    ...TYPOGRAPHY.button,
    color: COLORS.white,
  },
  disabledButton: {
    backgroundColor: COLORS.neutral[400],
    opacity: 0.7,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: SPACING.md,
    marginTop: SPACING.md,
  },
});
