import { StyleSheet, Dimensions } from "react-native";
import {
  COLORS,
  TYPOGRAPHY,
  SPACING,
  BORDER_RADIUS,
  SHADOWS,
} from "../../../constants/theme";

// Get screen dimensions for responsive design
const { width } = Dimensions.get('window');
const isTablet = width >= 768;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: isTablet ? SPACING.xl : SPACING.lg,
    paddingVertical: isTablet ? SPACING.lg : SPACING.md,
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerTitle: {
    ...TYPOGRAPHY.h2,
    color: COLORS.text,
    fontSize: isTablet ? TYPOGRAPHY.fontSize.xxxl : TYPOGRAPHY.fontSize.xl,
  },
  content: {
    flex: 1,
    paddingHorizontal: isTablet ? SPACING.xl : SPACING.lg,
    maxWidth: isTablet ? 800 : undefined,
    alignSelf: isTablet ? 'center' : undefined,
    width: isTablet ? '100%' : undefined,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: isTablet ? SPACING.xxl : SPACING.xl,
  },
  emptyText: {
    ...TYPOGRAPHY.body1,
    color: COLORS.textSecondary,
    textAlign: "center",
    marginBottom: isTablet ? SPACING.xl : SPACING.lg,
    fontSize: isTablet ? TYPOGRAPHY.fontSize.lg : TYPOGRAPHY.fontSize.md,
  },
  emptyIcon: {
    marginBottom: isTablet ? SPACING.xl : SPACING.lg,
    transform: [{ scale: isTablet ? 1.3 : 1 }],
  },
  fab: {
    position: "absolute",
    bottom: isTablet ? SPACING.xxl : SPACING.xl,
    right: isTablet ? SPACING.xxl : SPACING.xl,
    width: isTablet ? 64 : 56,
    height: isTablet ? 64 : 56,
    borderRadius: isTablet ? 32 : 28,
    backgroundColor: COLORS.primary.main,
    justifyContent: "center",
    alignItems: "center",
    ...SHADOWS.md,
  },
  fabText: {
    ...TYPOGRAPHY.button,
    color: COLORS.white,
    fontWeight: "bold",
    fontSize: isTablet ? TYPOGRAPHY.fontSize.md : TYPOGRAPHY.fontSize.sm,
  },
  errorContainer: {
    margin: isTablet ? SPACING.xl : SPACING.lg,
    padding: isTablet ? SPACING.lg : SPACING.md,
    backgroundColor: COLORS.danger[100],
    borderRadius: BORDER_RADIUS.md,
    alignItems: "center",
  },
  errorText: {
    ...TYPOGRAPHY.body2,
    color: COLORS.danger[600],
    marginBottom: isTablet ? SPACING.md : SPACING.sm,
    fontSize: isTablet ? TYPOGRAPHY.fontSize.md : TYPOGRAPHY.fontSize.sm,
  },
  retryButton: {
    paddingVertical: isTablet ? SPACING.sm : SPACING.xs,
    paddingHorizontal: isTablet ? SPACING.lg : SPACING.md,
    backgroundColor: COLORS.danger[500],
    borderRadius: BORDER_RADIUS.md,
  },
  retryText: {
    ...TYPOGRAPHY.button,
    color: COLORS.white,
    fontSize: isTablet ? TYPOGRAPHY.fontSize.md : TYPOGRAPHY.fontSize.sm,
  },
  offlineContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.warning[100],
    margin: isTablet ? SPACING.xl : SPACING.lg,
    padding: isTablet ? SPACING.lg : SPACING.md,
    borderRadius: BORDER_RADIUS.md,
  },
  offlineText: {
    ...TYPOGRAPHY.body2,
    color: COLORS.warning[600],
    marginLeft: isTablet ? SPACING.md : SPACING.sm,
    flex: 1,
    fontSize: isTablet ? TYPOGRAPHY.fontSize.md : TYPOGRAPHY.fontSize.sm,
  },
  fabDisabled: {
    backgroundColor: COLORS.textSecondary,
    opacity: 0.7,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: isTablet ? SPACING.xxl : SPACING.xl,
  },
  loadingText: {
    ...TYPOGRAPHY.body1,
    color: COLORS.textSecondary,
    marginTop: isTablet ? SPACING.lg : SPACING.md,
    fontSize: isTablet ? TYPOGRAPHY.fontSize.lg : TYPOGRAPHY.fontSize.md,
  },
  emptyImage: {
    width: isTablet ? 250 : 200,
    height: isTablet ? 250 : 200,
    marginBottom: isTablet ? SPACING.xl : SPACING.lg,
  },
  emptyTitle: {
    ...TYPOGRAPHY.h2,
    color: COLORS.text,
    marginBottom: isTablet ? SPACING.md : SPACING.sm,
    textAlign: "center",
    fontSize: isTablet ? TYPOGRAPHY.fontSize.xxxl : TYPOGRAPHY.fontSize.xl,
  },
  emptyDescription: {
    ...TYPOGRAPHY.body1,
    color: COLORS.neutral[600],
    marginBottom: isTablet ? SPACING.xl : SPACING.lg,
    textAlign: "center",
    fontSize: isTablet ? TYPOGRAPHY.fontSize.lg : TYPOGRAPHY.fontSize.md,
  },
  emptyButton: {
    flexDirection: "row",
    backgroundColor: COLORS.primary.main,
    paddingVertical: isTablet ? SPACING.lg : SPACING.md,
    paddingHorizontal: isTablet ? SPACING.xl : SPACING.lg,
    borderRadius: BORDER_RADIUS.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyButtonText: {
    ...TYPOGRAPHY.button,
    color: COLORS.white,
    fontSize: isTablet ? TYPOGRAPHY.fontSize.md : TYPOGRAPHY.fontSize.sm,
  },
  errorTitle: {
    ...TYPOGRAPHY.h2,
    color: COLORS.text,
    marginTop: isTablet ? SPACING.lg : SPACING.md,
    marginBottom: isTablet ? SPACING.md : SPACING.sm,
    textAlign: "center",
    fontSize: isTablet ? TYPOGRAPHY.fontSize.xxxl : TYPOGRAPHY.fontSize.xl,
  },
  errorDescription: {
    ...TYPOGRAPHY.body1,
    color: COLORS.neutral[600],
    marginBottom: isTablet ? SPACING.xl : SPACING.lg,
    textAlign: "center",
    fontSize: isTablet ? TYPOGRAPHY.fontSize.lg : TYPOGRAPHY.fontSize.md,
  },
  retryButtonText: {
    ...TYPOGRAPHY.button,
    color: COLORS.white,
    fontSize: isTablet ? TYPOGRAPHY.fontSize.md : TYPOGRAPHY.fontSize.sm,
  },
  offlineBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.warning[700],
    paddingVertical: isTablet ? SPACING.md : SPACING.sm,
    paddingHorizontal: isTablet ? SPACING.lg : SPACING.md,
  },
  offlineBannerText: {
    ...TYPOGRAPHY.caption,
    color: COLORS.white,
    marginLeft: isTablet ? SPACING.md : SPACING.sm,
    flex: 1,
    fontSize: isTablet ? TYPOGRAPHY.fontSize.sm : TYPOGRAPHY.fontSize.xs,
  },
  floatingButton: {
    position: "absolute",
    bottom: isTablet ? SPACING.xxl : SPACING.xl,
    right: isTablet ? SPACING.xl : SPACING.lg,
    width: isTablet ? 64 : 56,
    height: isTablet ? 64 : 56,
    borderRadius: isTablet ? 32 : 28,
    backgroundColor: COLORS.primary.main,
    justifyContent: "center",
    alignItems: "center",
    ...SHADOWS.lg,
    elevation: 5,
    zIndex: 100,
  },
});
